<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.3.2</Version>
    <Authors>Dev Proxy</Authors>
    <Title>Dev Proxy .NET Aspire extensions</Title>
    <Description>.NET Aspire extensions for adding Dev Proxy as a resource to your .NET Aspire application.</Description>
    <PackageId>DevProxy.Hosting</PackageId>
    <PackageTags>devproxy;aspire;dotnet;integration;hosting</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://aka.ms/devproxy</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dev-proxy-tools/aspire</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\assets\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.5.0" />
  </ItemGroup>

</Project>
